android.experimental.enableNewResourceShrinker.preciseShrinking=true
android.enableAppCompileTimeRClass=true
android.useAndroidX=true
android.enableR8.fullMode=false
org.gradle.jvmargs=-Xmx3000m -XX:MaxMetaspaceSize=384m
org.gradle.workers.max=1
org.gradle.parallel=false
kotlin.daemon.jvmargs=-Xmx1024m -XX:MaxMetaspaceSize=256m
systemProp.http.proxyHost=127.0.0.1
systemProp.http.proxyPort=18080
systemProp.https.proxyHost=127.0.0.1
systemProp.https.proxyPort=18080
